/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Usage */
        get: operations["get_usage_v1_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Job Events */
        get: operations["list_job_events_v1_jobs__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/github/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Github Repositories */
        get: operations["list_github_repositories_v1_github_repositories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Repositories */
        get: operations["list_repositories_v1_repositories_get"];
        put?: never;
        /** Connect Repository */
        post: operations["connect_repository_v1_repositories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repositories/{repository_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Repository */
        get: operations["get_repository_v1_repositories__repository_id__get"];
        put?: never;
        post?: never;
        /** Disconnect Repository */
        delete: operations["disconnect_repository_v1_repositories__repository_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repositories/{repository_id}/index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Index Repository */
        post: operations["index_repository_v1_repositories__repository_id__index_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repositories/{repository_id}/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Snapshots */
        get: operations["list_snapshots_v1_repositories__repository_id__snapshots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/snapshots/{snapshot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Snapshot */
        get: operations["get_snapshot_v1_snapshots__snapshot_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/snapshots/{snapshot_id}/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Coverage */
        get: operations["get_coverage_v1_snapshots__snapshot_id__coverage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/snapshots/{snapshot_id}/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tree
         * @description Immediate children of a directory; `path` is empty for the root.
         */
        get: operations["get_tree_v1_snapshots__snapshot_id__tree_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/snapshots/{snapshot_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get File
         * @description At most 1,000 lines of a file; defaults to lines 1 to 1,000.
         */
        get: operations["get_file_v1_snapshots__snapshot_id__file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search Snapshot
         * @description Text, path, symbol, or documentation search; exact path and symbol matches come first.
         */
        post: operations["search_snapshot_v1_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analysis-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_v1_analysis_runs_get"];
        put?: never;
        /** Submit Question */
        post: operations["submit_question_v1_analysis_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analysis-runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_v1_analysis_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccessOut
         * @description Access to the repository on GitHub, as last checked.
         */
        AccessOut: {
            /**
             * State
             * @enum {string}
             */
            state: "verified" | "lost" | "unknown";
            /** Reason */
            reason: string | null;
            /** Checked At */
            checked_at: string | null;
            /** Lost At */
            lost_at: string | null;
            /** Purge After */
            purge_after: string | null;
        };
        /** ActiveSnapshotOut */
        ActiveSnapshotOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Commit Sha */
            commit_sha: string;
            /** Branch */
            branch: string;
            /** Ready At */
            ready_at: string | null;
        };
        /** AnswerOut */
        AnswerOut: {
            /** Summary */
            summary: string;
            /** Claims */
            claims: components["schemas"]["ClaimOut"][];
            /** Gaps */
            gaps: string[];
        };
        /**
         * AutomaticUpdatesOut
         * @description Whether pushes and daily checks start runs (research R8).
         */
        AutomaticUpdatesOut: {
            /**
             * State
             * @enum {string}
             */
            state: "on" | "paused";
            /** Reason */
            reason: string | null;
        };
        /** CitationOut */
        CitationOut: {
            /** Label */
            label: string;
            /**
             * Source Type
             * @enum {string}
             */
            source_type: "symbol" | "code" | "doc";
            /** Path */
            path: string;
            /** Commit Sha */
            commit_sha: string;
            /** Start Line */
            start_line: number;
            /** End Line */
            end_line: number;
            /** Excerpt */
            excerpt: string;
            /** View Url */
            view_url: string;
        };
        /** ClaimOut */
        ClaimOut: {
            /** Text */
            text: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "fact" | "inference";
            /** Citations */
            citations: string[];
        };
        /** ConnectIn */
        ConnectIn: {
            /** Github Repository Id */
            github_repository_id: number;
            /** Branch */
            branch?: string | null;
            /**
             * Accept External Processing
             * @default false
             */
            accept_external_processing: boolean;
        };
        /** ConnectOut */
        ConnectOut: {
            repository: components["schemas"]["RepositoryOut"];
            job: components["schemas"]["JobRefOut"];
        };
        /** CoverageEntryOut */
        CoverageEntryOut: {
            /** Path */
            path: string;
            /**
             * Entry Type
             * @enum {string}
             */
            entry_type: "file" | "directory";
            /** Reason */
            reason: string;
            /** Detail */
            detail: string | null;
        };
        /** CoveragePage */
        CoveragePage: {
            /** Items */
            items: components["schemas"]["CoverageEntryOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** FileLinesOut */
        FileLinesOut: {
            /** Path */
            path: string;
            /** Commit Sha */
            commit_sha: string;
            /** Language */
            language: string;
            /** Line Count */
            line_count: number;
            /** Start Line */
            start_line: number;
            /** End Line */
            end_line: number;
            /** Lines */
            lines: string[];
        };
        /** GitHubRepositoryOut */
        GitHubRepositoryOut: {
            /** Github Repository Id */
            github_repository_id: number;
            /** Full Name */
            full_name: string;
            /** Private */
            private: boolean;
            /** Default Branch */
            default_branch: string;
            /** Connected Repository Id */
            connected_repository_id: string | null;
        };
        /** GitHubRepositoryPage */
        GitHubRepositoryPage: {
            /** Items */
            items: components["schemas"]["GitHubRepositoryOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IndexIn */
        IndexIn: {
            /** Branch */
            branch?: string | null;
            /**
             * Accept External Processing
             * @default false
             */
            accept_external_processing: boolean;
        };
        /** IndexOut */
        IndexOut: {
            job: components["schemas"]["JobRefOut"];
        };
        /** JobError */
        JobError: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Retryable */
            retryable: boolean;
        };
        /** JobEventResponse */
        JobEventResponse: {
            /** Seq */
            seq: number;
            /**
             * Event Type
             * @enum {string}
             */
            event_type: "queued" | "stage_started" | "stage_completed" | "retry_scheduled" | "succeeded" | "failed" | "canceled";
            /** Stage */
            stage: string | null;
            /** Message */
            message: string;
            /** Data */
            data: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** JobEventsResponse */
        JobEventsResponse: {
            /**
             * Job Status
             * @enum {string}
             */
            job_status: "queued" | "running" | "retry_wait" | "succeeded" | "failed" | "canceled";
            /** Items */
            items: components["schemas"]["JobEventResponse"][];
            /** Next After */
            next_after: number;
        };
        /** JobRefOut */
        JobRefOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status */
            status: string;
        };
        /** JobResponse */
        JobResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "index_repository" | "answer_question";
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "retry_wait" | "succeeded" | "failed" | "canceled";
            /**
             * Trigger
             * @enum {string}
             */
            trigger: "user" | "push" | "check";
            /** Attempt */
            attempt: number;
            /** Queued Behind */
            queued_behind: number | null;
            error: components["schemas"]["JobError"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
        };
        /** LatestJobOut */
        LatestJobOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status */
            status: string;
            /**
             * Trigger
             * @enum {string}
             */
            trigger: "user" | "push" | "check";
            error: components["schemas"]["JobError"] | null;
        };
        /**
         * LatestPushOut
         * @description The latest default-branch push received, and the job that covers it.
         */
        LatestPushOut: {
            /** Commit Sha */
            commit_sha: string;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            job: components["schemas"]["LatestJobOut"] | null;
        };
        /** MeOut */
        MeOut: {
            user: components["schemas"]["UserOut"];
            workspace: components["schemas"]["WorkspaceOut"];
            /** Github App Install Url */
            github_app_install_url: string;
        };
        /** RepositoryOut */
        RepositoryOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Full Name */
            full_name: string;
            /** Private */
            private: boolean;
            /** Default Branch */
            default_branch: string;
            /**
             * State
             * @enum {string}
             */
            state: "access_lost" | "indexing" | "ready" | "rejected" | "failed";
            access: components["schemas"]["AccessOut"];
            automatic_updates: components["schemas"]["AutomaticUpdatesOut"];
            active_snapshot: components["schemas"]["ActiveSnapshotOut"] | null;
            latest_indexing_job: components["schemas"]["LatestJobOut"] | null;
            latest_push: components["schemas"]["LatestPushOut"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** RepositoryPage */
        RepositoryPage: {
            /** Items */
            items: components["schemas"]["RepositoryOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** RunOut */
        RunOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Kind
             * @constant
             */
            kind: "repository_qa";
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "retry_wait" | "succeeded" | "failed" | "canceled";
            /** Quality State */
            quality_state: ("answered" | "insufficient_evidence") | null;
            /**
             * Repository Id
             * Format: uuid
             */
            repository_id: string;
            /**
             * Snapshot Id
             * Format: uuid
             */
            snapshot_id: string;
            /** Commit Sha */
            commit_sha: string;
            /** Question */
            question: string;
            answer: components["schemas"]["AnswerOut"] | null;
            /** Citations */
            citations: components["schemas"]["CitationOut"][];
            error: components["schemas"]["JobError"] | null;
            /** Job Id */
            job_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Completed At */
            completed_at: string | null;
        };
        /** RunPage */
        RunPage: {
            /** Items */
            items: components["schemas"]["RunSummaryOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** RunSummaryOut */
        RunSummaryOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Question */
            question: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "retry_wait" | "succeeded" | "failed" | "canceled";
            /** Quality State */
            quality_state: ("answered" | "insufficient_evidence") | null;
            /** Commit Sha */
            commit_sha: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SearchRequest */
        SearchRequest: {
            /**
             * Snapshot Id
             * Format: uuid
             */
            snapshot_id: string;
            /** Query */
            query: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "text" | "path" | "symbol" | "docs";
            /**
             * Limit
             * @default 20
             */
            limit: number;
        };
        /** SearchResponse */
        SearchResponse: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "text" | "path" | "symbol" | "docs";
            /** Degraded */
            degraded: boolean;
            /** Results */
            results: components["schemas"]["SearchResultOut"][];
        };
        /** SearchResultOut */
        SearchResultOut: {
            /** Path */
            path: string;
            /** Start Line */
            start_line: number;
            /** End Line */
            end_line: number;
            /** Snippet */
            snippet: string;
            symbol?: components["schemas"]["SearchSymbolOut"] | null;
            /** Exact */
            exact: boolean;
        };
        /** SearchSymbolOut */
        SearchSymbolOut: {
            /** Name */
            name: string;
            /** Kind */
            kind: string;
        };
        /** SnapshotDetailOut */
        SnapshotDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Repository Id
             * Format: uuid
             */
            repository_id: string;
            /** Commit Sha */
            commit_sha: string;
            /** Branch */
            branch: string;
            /** Status */
            status: string;
            /** Index Version */
            index_version: string;
            /** Coverage */
            coverage: {
                [key: string]: unknown;
            };
            /** Embeddings Available */
            embeddings_available: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Ready At */
            ready_at: string | null;
        };
        /** SnapshotOut */
        SnapshotOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Commit Sha */
            commit_sha: string;
            /** Branch */
            branch: string;
            /** Status */
            status: string;
            /** Is Active */
            is_active: boolean;
            /** Index Version */
            index_version: string;
            /** Coverage */
            coverage: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Ready At */
            ready_at: string | null;
            /** Trigger */
            trigger: ("user" | "push" | "check") | null;
        };
        /** SnapshotPage */
        SnapshotPage: {
            /** Items */
            items: components["schemas"]["SnapshotOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** SubmitIn */
        SubmitIn: {
            /**
             * Repository Id
             * Format: uuid
             */
            repository_id: string;
            /**
             * Kind
             * @default repository_qa
             * @constant
             */
            kind: "repository_qa";
            target?: components["schemas"]["TargetIn"];
            /** Question */
            question: string;
        };
        /** SubmitOut */
        SubmitOut: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "retry_wait" | "succeeded" | "failed" | "canceled";
            /**
             * Snapshot Id
             * Format: uuid
             */
            snapshot_id: string;
            /** Result Url */
            result_url: string;
            /** Events Url */
            events_url: string;
        };
        /** TargetIn */
        TargetIn: {
            /** Snapshot Id */
            snapshot_id?: string | null;
        };
        /** TreeEntryOut */
        TreeEntryOut: {
            /** Name */
            name: string;
            /**
             * Type
             * @enum {string}
             */
            type: "directory" | "file";
            /** Language */
            language?: string | null;
            /** Line Count */
            line_count?: number | null;
        };
        /** TreeOut */
        TreeOut: {
            /** Path */
            path: string;
            /** Entries */
            entries: components["schemas"]["TreeEntryOut"][];
        };
        /** UsageOut */
        UsageOut: {
            /**
             * Usage Date
             * Format: date
             */
            usage_date: string;
            /** Questions Used */
            questions_used: number;
            /** Questions Limit */
            questions_limit: number;
            /**
             * Resets At
             * Format: date-time
             */
            resets_at: string;
        };
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Github Login */
            github_login: string;
            /** Name */
            name: string | null;
            /** Avatar Url */
            avatar_url: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkspaceOut */
        WorkspaceOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_me_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    get_usage_v1_usage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageOut"];
                };
            };
        };
    };
    get_job_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_job_events_v1_jobs__job_id__events_get: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobEventsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_github_repositories_v1_github_repositories_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitHubRepositoryPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_repositories_v1_repositories_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    connect_repository_v1_repositories_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_repository_v1_repositories__repository_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disconnect_repository_v1_repositories__repository_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    index_repository_v1_repositories__repository_id__index_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["IndexIn"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_snapshots_v1_repositories__repository_id__snapshots_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_snapshot_v1_snapshots__snapshot_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_coverage_v1_snapshots__snapshot_id__coverage_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoveragePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tree_v1_snapshots__snapshot_id__tree_get: {
        parameters: {
            query?: {
                path?: string;
            };
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TreeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_file_v1_snapshots__snapshot_id__file_get: {
        parameters: {
            query: {
                path: string;
                start_line?: number | null;
                end_line?: number | null;
            };
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileLinesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_snapshot_v1_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_v1_analysis_runs_get: {
        parameters: {
            query: {
                repository_id: string;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_question_v1_analysis_runs_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_v1_analysis_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
