"""Source filters and spec limits (research R7, FR-009, FR-010)."""

import hashlib

import pytest

from codeatlas.config import Settings
from codeatlas.github.fake import (
    OVERSIZED_ID,
    SAMPLE_APP_ID,
    VENDORED_HEAVY_ID,
    commit_sha,
    get_fake_github,
)
from codeatlas.ingestion.extract import (
    ArchiveMember,
    LimitExceeded,
    RejectedMember,
    iter_archive,
)
from codeatlas.ingestion.filters import (
    EligibleFile,
    FilterResult,
    SkippedEntry,
    filter_members,
)

Member = ArchiveMember | RejectedMember


def _file(path: str, content: bytes = b"x = 1\n") -> ArchiveMember:
    return ArchiveMember(path=path, size=len(content), content=content)


def _large(path: str, size: int = 2_000_000) -> ArchiveMember:
    return ArchiveMember(path=path, size=size, content=None)


def _settings(**overrides: int) -> Settings:
    return Settings(_env_file=None, **overrides)  # type: ignore[arg-type]


def _filter(*members: Member, **limits: int) -> FilterResult:
    return filter_members(members, _settings(**limits))


def _reasons(result: FilterResult) -> dict[str, str]:
    return {entry.path: entry.reason for entry in result.skipped}


def _paths(result: FilterResult) -> list[str]:
    return [file.path for file in result.files]


@pytest.mark.parametrize(
    ("member", "reason"),
    [
        (RejectedMember("../escape.txt", "unsafe_path", "parent directory segment"), "unsafe_path"),
        (RejectedMember("docs-link", "link", "symbolic link"), "link"),
        (_file("vendor/lib.py"), "excluded_directory"),
        (_file("id_ed25519.pub"), "credential_file"),
        (_file("certs/server.pem"), "credential_file"),
        (_file("config/credentials-prod.json"), "credential_file"),
        (_file("yarn.lock"), "generated"),
        (_file("web/app.min.css"), "generated"),
        (_file("web/app.js.map"), "generated"),
        (
            _file("api/types.go", b"// Code generated by protoc. DO NOT EDIT.\npackage api\n"),
            "generated",
        ),
        (_file("assets/logo.png", b"\x89PNG\r\n\x1a\n\x00\x00"), "binary"),
        (_file("notes.txt", b"caf\xe9\n"), "unsupported_encoding"),
        (_large("data/large.txt"), "too_large"),
    ],
)
def test_each_rule_gives_its_reason(member: Member, reason: str) -> None:
    result = _filter(member)

    assert result.files == []
    assert [entry.reason for entry in result.skipped] == [reason]


@pytest.mark.parametrize(
    ("member", "reason"),
    [
        # Path safety comes before excluded directories.
        (RejectedMember("node_modules/.bin/tsc", "link", "symbolic link"), "link"),
        # Excluded directories come before credential files.
        (_file("node_modules/pkg/.env"), "excluded_directory"),
        # Credential files come before generated files.
        (_file("server.key", b"// @generated\n"), "credential_file"),
        # Generated files come before binary and encoding checks, and before size.
        (_file("bundle.min.js", b"\x00\x01"), "generated"),
        (_file("bundle.min.js", b"\xff\xfe"), "generated"),
        (_large("package-lock.json"), "generated"),
        # Binary comes before encoding.
        (_file("blob.bin", b"\xff\x00"), "binary"),
    ],
)
def test_the_first_matching_rule_decides(member: Member, reason: str) -> None:
    assert [entry.reason for entry in _filter(member).skipped] == [reason]


def test_an_excluded_directory_is_recorded_once() -> None:
    result = _filter(
        _file("node_modules/left-pad/index.js"),
        _file("node_modules/left-pad/package.json"),
        _file("node_modules/a/node_modules/b/index.js"),
        _file("web/node_modules/react/index.js"),
        _file("web/node_modules/react/package.json"),
        _file("app/__pycache__/main.cpython-313.pyc", b"\x00"),
        _file("build", b"not a directory\n"),
        _file("src/main.py"),
    )

    assert result.skipped == [
        SkippedEntry("app/__pycache__", "directory", "excluded_directory", None),
        SkippedEntry("node_modules", "directory", "excluded_directory", None),
        SkippedEntry("web/node_modules", "directory", "excluded_directory", None),
    ]
    assert _paths(result) == ["build", "src/main.py"]


def test_env_example_is_kept_and_other_env_files_are_not() -> None:
    result = _filter(
        _file(".env.example", b"API_TOKEN=\n"),
        _file(".env"),
        _file(".env.local"),
        _file("deploy/.ENV.production"),
        _file("id_rsa"),
    )

    assert _paths(result) == [".env.example"]
    assert set(_reasons(result).values()) == {"credential_file"}


def test_binary_and_encoding_checks() -> None:
    late_nul = b"a" * 9000 + b"\x00"
    result = _filter(
        _file("image.png", b"\x89PNG\x00"),
        _file("late-nul.txt", late_nul),
        _file("latin1.txt", b"caf\xe9\n"),
        _file("utf8.txt", "café\n".encode()),
    )

    assert _reasons(result) == {
        "image.png": "binary",
        "late-nul.txt": "binary",
        "latin1.txt": "unsupported_encoding",
    }
    assert result.files[0].content == "café\n"


def test_generated_markers_count_only_in_the_first_five_lines() -> None:
    within = b"\n" * 4 + b"// @generated by a tool\n"
    beyond = b"\n" * 5 + b"// @generated by a tool\n"
    result = _filter(
        _file("within.ts", within),
        _file("beyond.ts", beyond),
        _file("gen.go", b"// Code generated. DO NOT EDIT.\n"),
    )

    assert _reasons(result) == {"within.ts": "generated", "gen.go": "generated"}
    assert _paths(result) == ["beyond.ts"]


def test_gitattributes_linguist_generated_is_honored() -> None:
    attributes = (
        b"# generated code\n"
        b"*.ts text eol=lf\n"
        b"src/gen/*.ts linguist-generated\n"
        b"*.pb.py linguist-generated=true\n"
        b"docs/** linguist-generated\n"
        b"docs/keep.md -linguist-generated\n"
        b"/assets/** linguist-generated\n"
        b"tests/ linguist-generated\n"
    )
    result = _filter(
        _file("src/gen/client.ts"),
        _file("src/gen/nested/deep.ts"),
        _file("src/app.ts"),
        _file("api/v1/user.pb.py"),
        _file("docs/guide.md"),
        _file("docs/keep.md"),
        _file("assets/blob.bin", b"\x00"),
        _large("assets/huge.json"),
        _file("tests/test_app.py"),
        _file("web/.gitattributes", b"* linguist-generated\n"),
        # The root file is applied even when it comes last in the archive.
        _file(".gitattributes", attributes),
    )

    assert _reasons(result) == {
        "src/gen/client.ts": "generated",
        "api/v1/user.pb.py": "generated",
        "docs/guide.md": "generated",
        "assets/blob.bin": "generated",
        "assets/huge.json": "generated",
    }
    assert _paths(result) == [
        ".gitattributes",
        "docs/keep.md",
        "src/app.ts",
        "src/gen/nested/deep.ts",
        "tests/test_app.py",
        "web/.gitattributes",
    ]
    assert result.skipped[0].detail == "linguist-generated"


def test_a_large_file_is_too_large_unless_it_is_in_an_excluded_directory() -> None:
    result = _filter(_large("data/large.txt", 1_048_577), _large("node_modules/big/bundle.js"))

    assert result.skipped == [
        SkippedEntry("data/large.txt", "file", "too_large", "1048577 bytes"),
        SkippedEntry("node_modules", "directory", "excluded_directory", None),
    ]


def test_eligible_files_carry_language_lines_and_hash() -> None:
    result = _filter(
        _file("z.py", b"import os\nprint(os.name)"),
        _file("src/a.ts", b"export {};\n"),
        _file("src/b.TSX", b"<div />\n"),
        _file("README.md", b"# Title\n\nBody\n"),
        _file("docs/page.mdx", b"# Page\n"),
        _file("notes.txt", b""),
        _file("Makefile", b"all:\n\ttrue\n"),
    )

    assert [(file.path, file.language, file.line_count) for file in result.files] == [
        ("Makefile", "text", 2),
        ("README.md", "markdown", 3),
        ("docs/page.mdx", "markdown", 1),
        ("notes.txt", "text", 0),
        ("src/a.ts", "typescript", 1),
        ("src/b.TSX", "tsx", 1),
        ("z.py", "python", 2),
    ]
    python = result.files[-1]
    assert python == EligibleFile(
        path="z.py",
        language="python",
        content="import os\nprint(os.name)",
        size_bytes=24,
        line_count=2,
        content_sha256=hashlib.sha256(b"import os\nprint(os.name)").digest(),
    )
    assert result.source_lines == 10
    assert result.eligible_bytes == sum(file.size_bytes for file in result.files)


def test_results_are_sorted_by_path() -> None:
    result = _filter(_file("b.py"), _file(".env"), _file("a.py"), _file("A.lock"), _file(".env.1"))

    assert _paths(result) == ["A.lock", "a.py", "b.py"]
    assert [entry.path for entry in result.skipped] == [".env", ".env.1"]


# Fixed overhead per test below: excluded, credential, generated, binary, and too-large members.
_EXCLUDED = (
    _file("node_modules/a/index.js", b"1\n" * 50),
    _file("node_modules/b/index.js", b"1\n" * 50),
    _file(".env", b"1\n" * 50),
    _file("yarn.lock", b"1\n" * 50),
    _file("logo.png", b"\x00" * 100),
    _large("big.txt"),
)


@pytest.mark.parametrize(
    ("limit", "value", "members"),
    [
        ("max_files_per_snapshot", 2, [_file("a.py"), _file("b.py")]),
        ("max_expanded_bytes", 10, [_file("a.txt", b"12345"), _file("b.txt", b"12345")]),
        ("max_source_lines_per_snapshot", 3, [_file("a.txt", b"1\n2\n"), _file("b.txt", b"3")]),
    ],
)
def test_spec_limits_count_only_eligible_files(
    limit: str, value: int, members: list[ArchiveMember]
) -> None:
    result = _filter(*_EXCLUDED, *members, **{limit: value})
    assert len(result.files) == 2

    with pytest.raises(LimitExceeded) as raised:
        _filter(*_EXCLUDED, *members, _file("c.txt", b"x\n"), **{limit: value})

    assert raised.value.limit_name == limit
    assert raised.value.limit_value == value


# End to end over the fake GitHub archives -------------------------------------------------


def _filter_fake(full_name: str, repository_id: int, settings: Settings) -> FilterResult:
    fake = get_fake_github()
    sha = commit_sha(repository_id, "initial")
    with fake.open_tarball(fake.get_installation_id(full_name), full_name, sha) as stream:
        return filter_members(iter_archive(stream, settings), settings)


def test_sample_app_archive(settings: Settings) -> None:
    result = _filter_fake("octo-org/sample-app", SAMPLE_APP_ID, settings)

    assert {(entry.path, entry.entry_type, entry.reason) for entry in result.skipped} == {
        ("node_modules", "directory", "excluded_directory"),
        (".env", "file", "credential_file"),
        ("id_rsa", "file", "credential_file"),
        ("static/vendor.min.js", "file", "generated"),
        ("src/generated/apiClient.ts", "file", "generated"),
        ("assets/logo.png", "file", "binary"),
        ("docs/latin1-notes.txt", "file", "unsupported_encoding"),
        ("data/large.txt", "file", "too_large"),
    }
    languages = {file.path: file.language for file in result.files}
    assert languages[".env.example"] == "text"
    assert languages[".gitattributes"] == "text"
    assert languages["app/legacy.py"] == "python"
    assert languages["app/auth/access.py"] == "python"
    assert languages["src/types.ts"] == "typescript"
    assert languages["src/components/UserCard.tsx"] == "tsx"
    assert languages["README.md"] == "markdown"
    assert result.source_lines == sum(file.line_count for file in result.files)


def test_vendored_heavy_archive_passes_the_limits(settings: Settings) -> None:
    result = _filter_fake("octo-org/vendored-heavy", VENDORED_HEAVY_ID, settings)

    assert result.skipped == [SkippedEntry("node_modules", "directory", "excluded_directory", None)]
    assert _paths(result) == [
        "README.md",
        "app/__init__.py",
        "app/server.py",
        "docs/usage.md",
        "package.json",
        "src/index.ts",
    ]


def test_oversized_archive_exceeds_the_file_limit(settings: Settings) -> None:
    with pytest.raises(LimitExceeded) as raised:
        _filter_fake("octo-org/oversized", OVERSIZED_ID, settings)

    assert raised.value.limit_name == "max_files_per_snapshot"
